#version: '3.8'

services:
  backend:
    build: # Aqui la unica manera de hacerlo era con build teniendo en cuenta el docker compose up -d --build
      # o tambien se podia hacer solamente con image, pero como me daba cuenta del nombre de la imagen y donde
      # iba a quedar guardada. PREGUNTARLE AL PROFE. OJO.
      context: ./backend
      dockerfile: Dockerfile
    container_name: container-backend
    restart: unless-stopped
    ports:
        - "8080:8080"
    networks:
      - product-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/api/products || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: container-frontend
    restart: unless-stopped
    ports:
        - "3001:3000" # Primer puerto el del host, segundo puerto el del container. OJO
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - product-network

networks:
  product-network:
    driver: bridge
